-- Policy snapshot on sale items; normalize sale status to ACTIVE/VOIDED

ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS refundable BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS refund_window_days INTEGER NOT NULL DEFAULT 14;
ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS exchangeable BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS exchange_window_days INTEGER NOT NULL DEFAULT 14;
ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS restocking_fee_pct NUMERIC(6,2) NOT NULL DEFAULT 0;
ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS restocking_fee_flat NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS refund_proration_tiers JSONB NOT NULL DEFAULT '[]'::jsonb;

UPDATE sales SET status = 'ACTIVE' WHERE status = 'COMPLETED';
ALTER TABLE sales ALTER COLUMN status SET DEFAULT 'ACTIVE';
